services: ## Define um serviço
  backend: ## nome do serviço
    build: . ## localização do dockerfile
    command: npm start ## comando a executar
    ports:
      - "3000:3000" ## redirecionamento de porta quando chegar alguma requisição na porta 3000 chama o container na porta 3000
    environment:
      - DB_USER=root
      - DB_PASSWORD=1234
      - DB_NAME=campanha
      - DB_HOST=db
      - JWT_SECRET=1345
    volumes:
      - .:/app
    container_name: app_backend
    restart: always
    depends_on:
      - db

  db:
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: '1234'
    ports:
      -  3306:3306
    restart: always
